#==============#
# 相机参数 #
#==============#

Camera.name: "jingling4 1200"
Camera.setup: "monocular"
Camera.model: "perspective"

Camera.fx: 1447.6788
Camera.fy: 1626.2005
Camera.cx: 960
Camera.cy: 600
 
Camera.k1: -0.0548
Camera.k2: 0.0593
Camera.p1: 0
Camera.p2: 0
Camera.k3: 0
Camera.k4: 0

Initial.lat: 34.0263262222 
Initial.lon: 108.762782778 
Initial.alt: 418.254

Camera.fps: 10
Camera.cols: 1920
Camera.rows: 1200

Camera.color_order: "RGB"


#Initializer.num_min_triangulated_pts: 10
#Initializer.parallax_deg_threshold: 0.1
Feature.max_num_keypoints: 3000
#===========================#
# 显示参数 #
#===========================#

PangolinViewer.keyframe_size: 0.07
PangolinViewer.keyframe_line_width: 2
PangolinViewer.graph_line_width: 1
PangolinViewer.point_size: 2
PangolinViewer.camera_size: 0.08
PangolinViewer.camera_line_width: 3
PangolinViewer.viewpoint_x: 0
PangolinViewer.viewpoint_y: -0.65
PangolinViewer.viewpoint_z: -1.9
PangolinViewer.viewpoint_f: 400

#===========================#
# 紧急建图参数 #
#===========================#

Emergency.InputMap_type: "optimize" # map1 或者optimize
Emergency.DB_type: "0" # 0 或 1
 # 需要修改
Marker.Num: 0
